/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as PublicProjectProjectIdRouteImport } from './routes/public-project.$projectId'
import { Route as PublicAmcWorkspaceIdRouteImport } from './routes/public-amc.$workspaceId'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as InvitationAcceptInviteIdRouteImport } from './routes/invitation/accept.$inviteId'
import { Route as LayoutAuthenticatedProfileSetupRouteImport } from './routes/_layout/_authenticated/profile-setup'
import { Route as LayoutAuthenticatedOnboardingRouteImport } from './routes/_layout/_authenticated/onboarding'
import { Route as LayoutAuthenticatedInvitationsRouteImport } from './routes/_layout/_authenticated/invitations'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/settings'
import { Route as LayoutAuthenticatedDashboardInvitationsRouteImport } from './routes/_layout/_authenticated/dashboard/invitations'
import { Route as LayoutAuthenticatedDashboardWorkspaceCreateRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/create'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId'
import { Route as LayoutAuthenticatedDashboardSettingsZonesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/zones'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace'
import { Route as LayoutAuthenticatedDashboardSettingsAccountRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/sites'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/amc-dashboard'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceServicesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/services'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/roles'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/general'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/amc-bundles'
import { Route as LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/preferences'
import { Route as LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/notifications'
import { Route as LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/information'
import { Route as LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/developer'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/index'
import { Route as LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRouteImport } from './routes/_layout/_authenticated/dashboard/settings/zones/$zoneId/workflow'
import { Route as LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRouteImport } from './routes/_layout/_authenticated/dashboard/settings/zones/$zoneId/visibility'
import { Route as LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/settings/zones/$zoneId/members'
import { Route as LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/zones/$zoneId/integrations'
import { Route as LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/zones/$zoneId/general'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/gantt'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/board'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/backlog'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/amc'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId_'

const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeviceRoute,
} as any)
const PublicProjectProjectIdRoute = PublicProjectProjectIdRouteImport.update({
  id: '/public-project/$projectId',
  path: '/public-project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAmcWorkspaceIdRoute = PublicAmcWorkspaceIdRouteImport.update({
  id: '/public-amc/$workspaceId',
  path: '/public-amc/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const InvitationAcceptInviteIdRoute =
  InvitationAcceptInviteIdRouteImport.update({
    id: '/invitation/accept/$inviteId',
    path: '/invitation/accept/$inviteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedProfileSetupRoute =
  LayoutAuthenticatedProfileSetupRouteImport.update({
    id: '/profile-setup',
    path: '/profile-setup',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOnboardingRoute =
  LayoutAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedInvitationsRoute =
  LayoutAuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardInvitationsRoute =
  LayoutAuthenticatedDashboardInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceCreateRoute =
  LayoutAuthenticatedDashboardWorkspaceCreateRouteImport.update({
    id: '/workspace/create',
    path: '/workspace/create',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsZonesRoute =
  LayoutAuthenticatedDashboardSettingsZonesRouteImport.update({
    id: '/zones',
    path: '/zones',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountRoute =
  LayoutAuthenticatedDashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRouteImport.update(
    {
      id: '/amc-dashboard',
      path: '/amc-dashboard',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRouteImport.update({
    id: '/amc-bundles',
    path: '/amc-bundles',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute =
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute =
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountInformationRoute =
  LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute =
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute =
  LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRouteImport.update({
    id: '/$zoneId/workflow',
    path: '/$zoneId/workflow',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsZonesRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute =
  LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRouteImport.update({
    id: '/$zoneId/visibility',
    path: '/$zoneId/visibility',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsZonesRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute =
  LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRouteImport.update({
    id: '/$zoneId/members',
    path: '/$zoneId/members',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsZonesRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute =
  LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRouteImport.update(
    {
      id: '/$zoneId/integrations',
      path: '/$zoneId/integrations',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsZonesRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute =
  LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRouteImport.update({
    id: '/$zoneId/general',
    path: '/$zoneId/general',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsZonesRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRouteImport.update(
    {
      id: '/zone/$zoneId/',
      path: '/zone/$zoneId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRouteImport.update(
    {
      id: '/$siteId/',
      path: '/$siteId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRouteImport.update(
    {
      id: '/zone/$zoneId/gantt',
      path: '/zone/$zoneId/gantt',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRouteImport.update(
    {
      id: '/zone/$zoneId/board',
      path: '/zone/$zoneId/board',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRouteImport.update(
    {
      id: '/zone/$zoneId/backlog',
      path: '/zone/$zoneId/backlog',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRouteImport.update(
    {
      id: '/$siteId/amc',
      path: '/$siteId/amc',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRouteImport.update(
    {
      id: '/zone/$zoneId/task/$taskId_',
      path: '/zone/$zoneId/task/$taskId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-amc/$workspaceId': typeof PublicAmcWorkspaceIdRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/settings/zones': typeof LayoutAuthenticatedDashboardSettingsZonesRouteWithChildren
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/workspace/amc-bundles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/dashboard/settings/workspace/services': typeof LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute
  '/dashboard/workspace/$workspaceId/amc-dashboard': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId/sites': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteWithChildren
  '/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/zones/$zoneId/general': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute
  '/dashboard/settings/zones/$zoneId/integrations': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute
  '/dashboard/settings/zones/$zoneId/members': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute
  '/dashboard/settings/zones/$zoneId/visibility': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute
  '/dashboard/settings/zones/$zoneId/workflow': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/sites/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute
  '/dashboard/workspace/$workspaceId/sites/$siteId/amc': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute
  '/dashboard/workspace/$workspaceId/sites/$siteId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-amc/$workspaceId': typeof PublicAmcWorkspaceIdRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device': typeof DeviceIndexRoute
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/settings/zones': typeof LayoutAuthenticatedDashboardSettingsZonesRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/workspace/amc-bundles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/dashboard/settings/workspace/services': typeof LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute
  '/dashboard/workspace/$workspaceId/amc-dashboard': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/zones/$zoneId/general': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute
  '/dashboard/settings/zones/$zoneId/integrations': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute
  '/dashboard/settings/zones/$zoneId/members': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute
  '/dashboard/settings/zones/$zoneId/visibility': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute
  '/dashboard/settings/zones/$zoneId/workflow': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/sites': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute
  '/dashboard/workspace/$workspaceId/sites/$siteId/amc': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute
  '/dashboard/workspace/$workspaceId/sites/$siteId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute
  '/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-amc/$workspaceId': typeof PublicAmcWorkspaceIdRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/_authenticated/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/_layout/_authenticated/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/_layout/_authenticated/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/_layout/_authenticated/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/_layout/_authenticated/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/zones': typeof LayoutAuthenticatedDashboardSettingsZonesRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/_layout/_authenticated/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/_layout/_authenticated/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/_layout/_authenticated/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/_layout/_authenticated/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/_layout/_authenticated/dashboard/settings/workspace/amc-bundles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute
  '/_layout/_authenticated/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/_layout/_authenticated/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/_layout/_authenticated/dashboard/settings/workspace/services': typeof LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/amc-dashboard': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/_layout/_authenticated/dashboard/settings/zones/$zoneId/general': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute
  '/_layout/_authenticated/dashboard/settings/zones/$zoneId/integrations': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute
  '/_layout/_authenticated/dashboard/settings/zones/$zoneId/members': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute
  '/_layout/_authenticated/dashboard/settings/zones/$zoneId/visibility': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute
  '/_layout/_authenticated/dashboard/settings/zones/$zoneId/workflow': typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/amc': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId_': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-amc/$workspaceId'
    | '/public-project/$projectId'
    | '/device/'
    | '/dashboard'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/workspace'
    | '/dashboard/settings/zones'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/workspace/amc-bundles'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/settings/workspace/roles'
    | '/dashboard/settings/workspace/services'
    | '/dashboard/workspace/$workspaceId/amc-dashboard'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId/sites'
    | '/dashboard/workspace/$workspaceId/'
    | '/dashboard/settings/zones/$zoneId/general'
    | '/dashboard/settings/zones/$zoneId/integrations'
    | '/dashboard/settings/zones/$zoneId/members'
    | '/dashboard/settings/zones/$zoneId/visibility'
    | '/dashboard/settings/zones/$zoneId/workflow'
    | '/dashboard/workspace/$workspaceId/sites/'
    | '/dashboard/workspace/$workspaceId/sites/$siteId/amc'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/backlog'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/board'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/gantt'
    | '/dashboard/workspace/$workspaceId/sites/$siteId/'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-amc/$workspaceId'
    | '/public-project/$projectId'
    | '/device'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/account'
    | '/dashboard/settings/workspace'
    | '/dashboard/settings/zones'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/workspace/amc-bundles'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/settings/workspace/roles'
    | '/dashboard/settings/workspace/services'
    | '/dashboard/workspace/$workspaceId/amc-dashboard'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/settings/zones/$zoneId/general'
    | '/dashboard/settings/zones/$zoneId/integrations'
    | '/dashboard/settings/zones/$zoneId/members'
    | '/dashboard/settings/zones/$zoneId/visibility'
    | '/dashboard/settings/zones/$zoneId/workflow'
    | '/dashboard/workspace/$workspaceId/sites'
    | '/dashboard/workspace/$workspaceId/sites/$siteId/amc'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/backlog'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/board'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/gantt'
    | '/dashboard/workspace/$workspaceId/sites/$siteId'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId'
    | '/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/_layout/_authenticated'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-amc/$workspaceId'
    | '/public-project/$projectId'
    | '/device/'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/invitations'
    | '/_layout/_authenticated/onboarding'
    | '/_layout/_authenticated/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/_layout/_authenticated/dashboard/invitations'
    | '/_layout/_authenticated/dashboard/settings'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/dashboard/settings/account'
    | '/_layout/_authenticated/dashboard/settings/workspace'
    | '/_layout/_authenticated/dashboard/settings/zones'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId'
    | '/_layout/_authenticated/dashboard/workspace/create'
    | '/_layout/_authenticated/dashboard/settings/account/developer'
    | '/_layout/_authenticated/dashboard/settings/account/information'
    | '/_layout/_authenticated/dashboard/settings/account/notifications'
    | '/_layout/_authenticated/dashboard/settings/account/preferences'
    | '/_layout/_authenticated/dashboard/settings/workspace/amc-bundles'
    | '/_layout/_authenticated/dashboard/settings/workspace/general'
    | '/_layout/_authenticated/dashboard/settings/workspace/roles'
    | '/_layout/_authenticated/dashboard/settings/workspace/services'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/amc-dashboard'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
    | '/_layout/_authenticated/dashboard/settings/zones/$zoneId/general'
    | '/_layout/_authenticated/dashboard/settings/zones/$zoneId/integrations'
    | '/_layout/_authenticated/dashboard/settings/zones/$zoneId/members'
    | '/_layout/_authenticated/dashboard/settings/zones/$zoneId/visibility'
    | '/_layout/_authenticated/dashboard/settings/zones/$zoneId/workflow'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/amc'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/backlog'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/board'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/gantt'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId_'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DeviceRoute: typeof DeviceRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
  PublicAmcWorkspaceIdRoute: typeof PublicAmcWorkspaceIdRoute
  PublicProjectProjectIdRoute: typeof PublicProjectProjectIdRoute
  InvitationAcceptInviteIdRoute: typeof InvitationAcceptInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/public-project/$projectId': {
      id: '/public-project/$projectId'
      path: '/public-project/$projectId'
      fullPath: '/public-project/$projectId'
      preLoaderRoute: typeof PublicProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-amc/$workspaceId': {
      id: '/public-amc/$workspaceId'
      path: '/public-amc/$workspaceId'
      fullPath: '/public-amc/$workspaceId'
      preLoaderRoute: typeof PublicAmcWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/invitation/accept/$inviteId': {
      id: '/invitation/accept/$inviteId'
      path: '/invitation/accept/$inviteId'
      fullPath: '/invitation/accept/$inviteId'
      preLoaderRoute: typeof InvitationAcceptInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/profile-setup': {
      id: '/_layout/_authenticated/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof LayoutAuthenticatedProfileSetupRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/onboarding': {
      id: '/_layout/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutAuthenticatedOnboardingRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/invitations': {
      id: '/_layout/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings': {
      id: '/_layout/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/invitations': {
      id: '/_layout/_authenticated/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/create': {
      id: '/_layout/_authenticated/dashboard/workspace/create'
      path: '/workspace/create'
      fullPath: '/dashboard/workspace/create'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/dashboard/workspace/$workspaceId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/zones': {
      id: '/_layout/_authenticated/dashboard/settings/zones'
      path: '/zones'
      fullPath: '/dashboard/settings/zones'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsZonesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace': {
      id: '/_layout/_authenticated/dashboard/settings/workspace'
      path: '/workspace'
      fullPath: '/dashboard/settings/workspace'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/account': {
      id: '/_layout/_authenticated/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites'
      path: '/sites'
      fullPath: '/dashboard/workspace/$workspaceId/sites'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
      path: '/search'
      fullPath: '/dashboard/workspace/$workspaceId/search'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/dashboard/workspace/$workspaceId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/amc-dashboard': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/amc-dashboard'
      path: '/amc-dashboard'
      fullPath: '/dashboard/workspace/$workspaceId/amc-dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/services': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/services'
      path: '/services'
      fullPath: '/dashboard/settings/workspace/services'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceServicesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/roles': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/roles'
      path: '/roles'
      fullPath: '/dashboard/settings/workspace/roles'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/general': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/general'
      path: '/general'
      fullPath: '/dashboard/settings/workspace/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/amc-bundles': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/amc-bundles'
      path: '/amc-bundles'
      fullPath: '/dashboard/settings/workspace/amc-bundles'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/preferences': {
      id: '/_layout/_authenticated/dashboard/settings/account/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/account/preferences'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/notifications': {
      id: '/_layout/_authenticated/dashboard/settings/account/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/account/notifications'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/information': {
      id: '/_layout/_authenticated/dashboard/settings/account/information'
      path: '/information'
      fullPath: '/dashboard/settings/account/information'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/developer': {
      id: '/_layout/_authenticated/dashboard/settings/account/developer'
      path: '/developer'
      fullPath: '/dashboard/settings/account/developer'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/sites/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute
    }
    '/_layout/_authenticated/dashboard/settings/zones/$zoneId/workflow': {
      id: '/_layout/_authenticated/dashboard/settings/zones/$zoneId/workflow'
      path: '/$zoneId/workflow'
      fullPath: '/dashboard/settings/zones/$zoneId/workflow'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsZonesRoute
    }
    '/_layout/_authenticated/dashboard/settings/zones/$zoneId/visibility': {
      id: '/_layout/_authenticated/dashboard/settings/zones/$zoneId/visibility'
      path: '/$zoneId/visibility'
      fullPath: '/dashboard/settings/zones/$zoneId/visibility'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsZonesRoute
    }
    '/_layout/_authenticated/dashboard/settings/zones/$zoneId/members': {
      id: '/_layout/_authenticated/dashboard/settings/zones/$zoneId/members'
      path: '/$zoneId/members'
      fullPath: '/dashboard/settings/zones/$zoneId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsZonesRoute
    }
    '/_layout/_authenticated/dashboard/settings/zones/$zoneId/integrations': {
      id: '/_layout/_authenticated/dashboard/settings/zones/$zoneId/integrations'
      path: '/$zoneId/integrations'
      fullPath: '/dashboard/settings/zones/$zoneId/integrations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsZonesRoute
    }
    '/_layout/_authenticated/dashboard/settings/zones/$zoneId/general': {
      id: '/_layout/_authenticated/dashboard/settings/zones/$zoneId/general'
      path: '/$zoneId/general'
      fullPath: '/dashboard/settings/zones/$zoneId/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsZonesRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/'
      path: '/zone/$zoneId'
      fullPath: '/dashboard/workspace/$workspaceId/zone/$zoneId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/'
      path: '/$siteId'
      fullPath: '/dashboard/workspace/$workspaceId/sites/$siteId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/gantt': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/gantt'
      path: '/zone/$zoneId/gantt'
      fullPath: '/dashboard/workspace/$workspaceId/zone/$zoneId/gantt'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/board': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/board'
      path: '/zone/$zoneId/board'
      fullPath: '/dashboard/workspace/$workspaceId/zone/$zoneId/board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/backlog': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/backlog'
      path: '/zone/$zoneId/backlog'
      fullPath: '/dashboard/workspace/$workspaceId/zone/$zoneId/backlog'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/amc': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/sites/$siteId/amc'
      path: '/$siteId/amc'
      fullPath: '/dashboard/workspace/$workspaceId/sites/$siteId/amc'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId_': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId_'
      path: '/zone/$zoneId/task/$taskId'
      fullPath: '/dashboard/workspace/$workspaceId/zone/$zoneId/task/$taskId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
  }
}

interface LayoutAuthenticatedDashboardSettingsAccountRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  LayoutAuthenticatedDashboardSettingsAccountInformationRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
}

const LayoutAuthenticatedDashboardSettingsAccountRouteChildren: LayoutAuthenticatedDashboardSettingsAccountRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute:
      LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute,
    LayoutAuthenticatedDashboardSettingsAccountInformationRoute:
      LayoutAuthenticatedDashboardSettingsAccountInformationRoute,
    LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute:
      LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute,
    LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute:
      LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute,
  }

const LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsAccountRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsAccountRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren {
  LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute
}

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren: LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceAmcBundlesRoute,
    LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute,
    LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute,
    LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceServicesRoute,
  }

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsZonesRouteChildren {
  LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute
  LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute
  LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute
  LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute
  LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute: typeof LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute
}

const LayoutAuthenticatedDashboardSettingsZonesRouteChildren: LayoutAuthenticatedDashboardSettingsZonesRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute:
      LayoutAuthenticatedDashboardSettingsZonesZoneIdGeneralRoute,
    LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute:
      LayoutAuthenticatedDashboardSettingsZonesZoneIdIntegrationsRoute,
    LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute:
      LayoutAuthenticatedDashboardSettingsZonesZoneIdMembersRoute,
    LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute:
      LayoutAuthenticatedDashboardSettingsZonesZoneIdVisibilityRoute,
    LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute:
      LayoutAuthenticatedDashboardSettingsZonesZoneIdWorkflowRoute,
  }

const LayoutAuthenticatedDashboardSettingsZonesRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsZonesRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsZonesRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  LayoutAuthenticatedDashboardSettingsZonesRoute: typeof LayoutAuthenticatedDashboardSettingsZonesRouteWithChildren
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountRoute:
      LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsWorkspaceRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsZonesRoute:
      LayoutAuthenticatedDashboardSettingsZonesRouteWithChildren,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdAmcRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesSiteIdIndexRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteWithChildren
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdAmcDashboardRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSitesRouteWithChildren,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBacklogRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdBoardRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdGanttRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdZoneZoneIdTaskTaskIdRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardInvitationsRoute: typeof LayoutAuthenticatedDashboardInvitationsRoute
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  LayoutAuthenticatedDashboardWorkspaceCreateRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardInvitationsRoute:
      LayoutAuthenticatedDashboardInvitationsRoute,
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren,
    LayoutAuthenticatedDashboardWorkspaceCreateRoute:
      LayoutAuthenticatedDashboardWorkspaceCreateRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedInvitationsRoute: typeof LayoutAuthenticatedInvitationsRoute
  LayoutAuthenticatedOnboardingRoute: typeof LayoutAuthenticatedOnboardingRoute
  LayoutAuthenticatedProfileSetupRoute: typeof LayoutAuthenticatedProfileSetupRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedInvitationsRoute: LayoutAuthenticatedInvitationsRoute,
  LayoutAuthenticatedOnboardingRoute: LayoutAuthenticatedOnboardingRoute,
  LayoutAuthenticatedProfileSetupRoute: LayoutAuthenticatedProfileSetupRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DeviceRouteChildren {
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DeviceRoute: DeviceRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
  PublicAmcWorkspaceIdRoute: PublicAmcWorkspaceIdRoute,
  PublicProjectProjectIdRoute: PublicProjectProjectIdRoute,
  InvitationAcceptInviteIdRoute: InvitationAcceptInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
